spring.application.name=backend

sever.port=8080

ai.service.url=http://localhost:8000

spring.devtools.add-properties=false

spring.datasource.url=jdbc:postgresql://localhost:5432/navora
spring.datasource.username=navora_user
spring.datasource.password=navora_pass

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=its-been-a-long-day-without-you-my-friend-i-will-tell-you-all-about-it-when-i-see-you-again
jwt.expiration-ms=86400000

minio.endpoint=http://localhost:9000
minio.access-key= navora_minio
minio.secret-key=navora_minio_pass
minio.bucket-name=scan-images
